# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

#shared:
# api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 742f6239c979d146a768df42025283ca7e7cecda4ad90cb70d3701276c0bb49899413d6ee837ddd5f9d6553cc6e02cad9910e9a45d0dd129b7fa91fdcf007945

test:
  secret_key_base: ab82cf002ebce715892c6cb464a1d222ae4437a8d10c0e50546a5cbec6c5463579a452785efee94a41811d5de4a7fb6901f23b8da7fa9b325bd7411fc52eb480

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: "use secrets.yml.enc to store this"
